{{- if .Values.jupyterPublishService.createServiceAccount -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jupyterPublishService.serviceAccountName | quote }}
  namespace: {{ .Values.jupyterPublishService.namespace | quote }}
  labels:
    app: {{ .Values.jupyterPublishService.appName | quote }}
{{- end -}}
